### ISSUE TITLE
Text format compatibility

### ISSUE THREAD

**Issue by sunfishcode** [yurydelendik/wasmtext#1]
I fed the output of wasmtext on the ".out" files in the testsuite into wabt's wast2wasm. A lot of things worked, but there were some variations. Here are the most common differences I encountered:

Imports; wabt expects the function name inside the `(func`, eg:
```diff
-  (import $import0 "spectest" "print" (func (param i32)))
+  (import "spectest" "print" (func $import0 (param i32)))
 ```

Exports; same as above, eg:
```diff
-  (export "good" $func1)
+  (export "good" (func $func1))
```

Offset fields are unsigned, eg:
```diff
-    i32.load offset=-1
+    i32.load offset=4294967295
```

NaN is spelled `nan` and positive NaN doesn't get a '+', eg:
```diff
-    f64.const +NaN
+    f64.const nan
```

Block/if/etc. signatures were recently changed from `block i32` to `block (result i32)`, eg:
```diff
-    if f32
+    if (result f32)
```

**Comment by yurydelendik** [comment]
Thanks.

Fixed in 0.1.2
